### ISSUE TITLE
Code won't compile and verify

### ISSUE THREAD

**Issue by sleepingzombie** [SeekND/CaptureTheFlag#1]
Hey man, I just built one of these and was desperate to try it out. Went to upload the code to my Arduino Nano and got nothing but error messages. Doesn't matter if I try installing Alpha 4 or alpha 3. Here's what the compiler kicked out...

`Arduino: 1.8.5 (Windows 10), Board: "Arduino Nano, ATmega328P"

In file included from C:\ctf\ctf.ino:102:0:

C:\Users\sleep\Documents\Arduino\libraries\FastLED/FastLED.h:12:2: warning: #warning FastLED version 3.001.000 (Not really a warning, just telling you here.) [-Wcpp]

 #warning FastLED version 3.001.000  (Not really a warning, just telling you here.)

  ^

In file included from C:\ctf\ctf.ino:260:0:

sketch\leds.h:73:8: warning: character constant too long for its type

   if ( pilot1 == 'blue' && channelIndex == 0 && isBlue == 0 )

        ^

sketch\leds.h:73:18: warning: character constant too long for its type

   if ( pilot1 == 'blue' && channelIndex == 0 && isBlue == 0 )

                  ^

sketch\leds.h:91:13: warning: character constant too long for its type

   else if ( pilot1 == 'red' && channelIndex == 0 && isRed == 0  )

             ^

sketch\leds.h:91:23: warning: character constant too long for its type

   else if ( pilot1 == 'red' && channelIndex == 0 && isRed == 0  )

                       ^

sketch\leds.h:108:13: warning: character constant too long for its type

   else if ( pilot2 == 'blue' && channelIndex == 1 && isBlue == 0  )

             ^

sketch\leds.h:108:23: warning: character constant too long for its type

   else if ( pilot2 == 'blue' && channelIndex == 1 && isBlue == 0  )

                       ^

sketch\leds.h:125:13: warning: character constant too long for its type

   else if ( pilot2 == 'red' && channelIndex == 1 && isRed == 0  )

             ^

sketch\leds.h:125:23: warning: character constant too long for its type

   else if ( pilot2 == 'red' && channelIndex == 1 && isRed == 0  )

                       ^

sketch\leds.h:143:8: warning: character constant too long for its type

   if ( pilot3 == 'blue' && channelIndex == 2 && isBlue == 0  )

        ^

sketch\leds.h:143:18: warning: character constant too long for its type

   if ( pilot3 == 'blue' && channelIndex == 2 && isBlue == 0  )

                  ^

sketch\leds.h:160:13: warning: character constant too long for its type

   else if ( pilot3 == 'red' && channelIndex == 2 && isRed == 0  )

             ^

sketch\leds.h:160:23: warning: character constant too long for its type

   else if ( pilot3 == 'red' && channelIndex == 2 && isRed == 0  )

                       ^

sketch\leds.h:177:8: warning: character constant too long for its type

   if ( pilot4 == 'blue' && channelIndex == 3 && isBlue == 0 )

        ^

sketch\leds.h:177:18: warning: character constant too long for its type

   if ( pilot4 == 'blue' && channelIndex == 3 && isBlue == 0 )

                  ^

sketch\leds.h:194:13: warning: character constant too long for its type

   else if ( pilot4 == 'red' && channelIndex == 3 && isRed == 0  )

             ^

sketch\leds.h:194:23: warning: character constant too long for its type

   else if ( pilot4 == 'red' && channelIndex == 3 && isRed == 0  )

                       ^

sketch\leds.h:211:8: warning: character constant too long for its type

   if ( pilot5 == 'blue' && channelIndex == 4 && isBlue == 0 )

        ^

sketch\leds.h:211:18: warning: character constant too long for its type

   if ( pilot5 == 'blue' && channelIndex == 4 && isBlue == 0 )

                  ^

sketch\leds.h:228:13: warning: character constant too long for its type

   else if ( pilot5 == 'red' && channelIndex == 4 && isRed == 0  )

             ^

sketch\leds.h:228:23: warning: character constant too long for its type

   else if ( pilot5 == 'red' && channelIndex == 4 && isRed == 0  )

                       ^

sketch\leds.h:245:8: warning: character constant too long for its type

   if ( pilot6 == 'blue' && channelIndex == 5 && isBlue == 0  )

        ^

sketch\leds.h:245:18: warning: character constant too long for its type

   if ( pilot6 == 'blue' && channelIndex == 5 && isBlue == 0  )

                  ^

sketch\leds.h:262:13: warning: character constant too long for its type

   else if ( pilot6 == 'red' && channelIndex == 5 && isRed == 0  )

             ^

sketch\leds.h:262:23: warning: character constant too long for its type

   else if ( pilot6 == 'red' && channelIndex == 5 && isRed == 0  )

                       ^

sketch\leds.h:279:8: warning: character constant too long for its type

   if ( pilot7 == 'blue' && channelIndex == 6 && isBlue == 0  )

        ^

sketch\leds.h:279:18: warning: character constant too long for its type

   if ( pilot7 == 'blue' && channelIndex == 6 && isBlue == 0  )

                  ^

sketch\leds.h:296:13: warning: character constant too long for its type

   else if ( pilot7 == 'red' && channelIndex == 6 && isRed == 0  )

             ^

sketch\leds.h:296:23: warning: character constant too long for its type

   else if ( pilot7 == 'red' && channelIndex == 6 && isRed == 0  )

                       ^

sketch\leds.h:313:8: warning: character constant too long for its type

   if ( pilot8 == 'blue' && channelIndex == 7 && isBlue == 0  )

        ^

sketch\leds.h:313:18: warning: character constant too long for its type

   if ( pilot8 == 'blue' && channelIndex == 7 && isBlue == 0  )

                  ^

sketch\leds.h:330:13: warning: character constant too long for its type

   else if ( pilot8 == 'red' && channelIndex == 7 && isRed == 0  )

             ^

sketch\leds.h:330:23: warning: character constant too long for its type

   else if ( pilot8 == 'red' && channelIndex == 7 && isRed == 0  )

                       ^

sketch\leds.h:351:8: warning: character constant too long for its type

   if ( pilot1 == 'blue' && isBlue == 0 && channelIndex == 0 )

        ^

sketch\leds.h:351:18: warning: character constant too long for its type

   if ( pilot1 == 'blue' && isBlue == 0 && channelIndex == 0 )

                  ^

sketch\leds.h:357:13: warning: character constant too long for its type

   else if ( pilot1 == 'red' && isRed == 0 && channelIndex == 0 )

             ^

sketch\leds.h:357:23: warning: character constant too long for its type

   else if ( pilot1 == 'red' && isRed == 0 && channelIndex == 0 )

                       ^

sketch\leds.h:363:13: warning: character constant too long for its type

   else if ( pilot2 == 'blue' && isBlue == 0 && channelIndex == 1 )

             ^

sketch\leds.h:363:23: warning: character constant too long for its type

   else if ( pilot2 == 'blue' && isBlue == 0 && channelIndex == 1 )

                       ^

sketch\leds.h:369:13: warning: character constant too long for its type

   else if ( pilot2 == 'red' && isRed == 0 && channelIndex == 1 )

             ^

sketch\leds.h:369:23: warning: character constant too long for its type

   else if ( pilot2 == 'red' && isRed == 0 && channelIndex == 1 )

                       ^

sketch\leds.h:375:13: warning: character constant too long for its type

   else if ( pilot3 == 'blue' && isBlue == 0 && channelIndex == 2 )

             ^

sketch\leds.h:375:23: warning: character constant too long for its type

   else if ( pilot3 == 'blue' && isBlue == 0 && channelIndex == 2 )

                       ^

sketch\leds.h:381:13: warning: character constant too long for its type

   else if ( pilot3 == 'red' && isRed == 0 && channelIndex == 2 )

             ^

sketch\leds.h:381:23: warning: character constant too long for its type

   else if ( pilot3 == 'red' && isRed == 0 && channelIndex == 2 )

                       ^

sketch\leds.h:387:13: warning: character constant too long for its type

   else if ( pilot4 == 'blue' && isBlue == 0 && channelIndex == 3 )

             ^

sketch\leds.h:387:23: warning: character constant too long for its type

   else if ( pilot4 == 'blue' && isBlue == 0 && channelIndex == 3 )

                       ^

sketch\leds.h:393:13: warning: character constant too long for its type

   else if ( pilot4 == 'red' && isRed == 0 && channelIndex == 3 )

             ^

sketch\leds.h:393:23: warning: character constant too long for its type

   else if ( pilot4 == 'red' && isRed == 0 && channelIndex == 3 )

                       ^

sketch\leds.h:399:13: warning: character constant too long for its type

   else if ( pilot5 == 'blue' && isBlue == 0 && channelIndex == 4 )

             ^

sketch\leds.h:399:23: warning: character constant too long for its type

   else if ( pilot5 == 'blue' && isBlue == 0 && channelIndex == 4 )

                       ^

sketch\leds.h:405:13: warning: character constant too long for its type

   else if ( pilot5 == 'red' && isRed == 0 && channelIndex == 4 )

             ^

sketch\leds.h:405:23: warning: character constant too long for its type

   else if ( pilot5 == 'red' && isRed == 0 && channelIndex == 4 )

                       ^

sketch\leds.h:411:13: warning: character constant too long for its type

   else if ( pilot6 == 'blue' && isBlue == 0 && channelIndex == 5 )

             ^

sketch\leds.h:411:23: warning: character constant too long for its type

   else if ( pilot6 == 'blue' && isBlue == 0 && channelIndex == 5 )

                       ^

sketch\leds.h:417:13: warning: character constant too long for its type

   else if ( pilot6 == 'red' && isRed == 0 && channelIndex == 5 )

             ^

sketch\leds.h:417:23: warning: character constant too long for its type

   else if ( pilot6 == 'red' && isRed == 0 && channelIndex == 5 )

                       ^

sketch\leds.h:423:13: warning: character constant too long for its type

   else if ( pilot7 == 'blue' && isBlue == 0 && channelIndex == 6 )

             ^

sketch\leds.h:423:23: warning: character constant too long for its type

   else if ( pilot7 == 'blue' && isBlue == 0 && channelIndex == 6 )

                       ^

sketch\leds.h:429:13: warning: character constant too long for its type

   else if ( pilot7 == 'red' && isRed == 0 && channelIndex == 6 )

             ^

sketch\leds.h:429:23: warning: character constant too long for its type

   else if ( pilot7 == 'red' && isRed == 0 && channelIndex == 6 )

                       ^

sketch\leds.h:435:13: warning: character constant too long for its type

   else if ( pilot8 == 'blue' && isBlue == 0 && channelIndex == 7 )

             ^

sketch\leds.h:435:23: warning: character constant too long for its type

   else if ( pilot8 == 'blue' && isBlue == 0 && channelIndex == 7 )

                       ^

sketch\leds.h:441:13: warning: character constant too long for its type

   else if ( pilot8 == 'red' && isRed == 0 && channelIndex == 7 )

             ^

sketch\leds.h:441:23: warning: character constant too long for its type

   else if ( pilot8 == 'red' && isRed == 0 && channelIndex == 7 )

                       ^

C:\Users\sleep\AppData\Local\Temp\ccExqwZc.s: Assembler messages:

C:\Users\sleep\AppData\Local\Temp\ccExqwZc.s:1020: Warning: ignoring changed section attributes for .progmem.data

Sketch uses 8012 bytes (26%) of program storage space. Maximum is 30720 bytes.
Global variables use 351 bytes (17%) of dynamic memory, leaving 1697 bytes for local variables. Maximum is 2048 bytes.
avrdude: ser_open(): can't open device "\\.\COM4": The system cannot find the file specified.

Problem uploading to board.  See http://www.arduino.cc/en/Guide/Troubleshooting#upload for suggestions.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

`

**Comment by SeekND** [comment]
Hi there.
It seems you have the wrong port selected to upload to the board. Check what should be the correct port for your nano.
Also if you import the new code you should no longer have those "character constant too long" messages anymore :)

Let me know if this fixed it.

**Comment by sleepingzombie** [comment]
Had to re-install the Arduino tools but the new code works perfectly. Can't wait to test it out, thanks for the help.

**Comment by SeekND** [comment]
Awesome!
Hope you enjoy it :)
